SCB_AUTO_RES=1
SCB_GAMESCOPE_ARGS="-f --rt --grab --force-grab-cursor --backend wayland --prefer-vk-device 10de:2203"

# Force DXVK (DX9/DX10/DX11) games to use RTX 3090 Ti
export DXVK_FILTER_DEVICE_NAME="RTX 3090"
