# All distroboxes
#
# Build all with - distrobox assemble create --file distrobox.ini
#
# Each container stores its home directory in a separate directory from host to avoid dotfile pollution and other issues.
# Configure this at ~/.config/distrobox/distrobox.conf
#
# each init_hooks entry starts with `sudo -u \#1000 ` to make sure we aren't running bash scripts as root.

# Main development box
[dev-box]
image=archlinux:latest
pull=true
root=false
entry=false
nvidia=true
volume=/run/user/1000/podman/podman.sock:/var/run/docker.sock
init_hooks="sudo -u \#1000 bash ${HOME}/repos/coulomb/distrobox/init-dev-box.sh"
exported_apps=code
exported_bins=/usr/bin/code /Android/Sdk/emulator/emulator /Android/Sdk/platform-tools/adb

# CTF environment
[ctf-box]
image=docker.io/kalilinux/kali-rolling:latest
pull=true
root=false
entry=false
volume=/run/user/1000/podman/podman.sock:/var/run/docker.sock
init_hooks="sudo -u \#1000 bash ${HOME}/repos/coulomb/distrobox/init-ctf-box.sh"
exported_apps=ghidra burpsuite wireshark
exported_bins=/usr/bin/ghidra /usr/bin/burpsuite /usr/bin/wireshark

# FPGA and embedded development
[embed-box]
image=ubuntu:22.04
pull=true
root=false
entry=false
init_hooks="sudo -u \#1000 bash ${HOME}/repos/coulomb/distrobox/init-embed-box.sh"
exported_apps=pulseview gtkwave
exported_bins=/usr/bin/pulseview /usr/bin/gtkwave

# Game development
[gamedev-box]
image=ubuntu:22.04
pull=true
root=false
entry=false
nvidia=true
init_hooks="sudo -u \#1000 bash ${HOME}/repos/coulomb/distrobox/init-gamedev-box.sh"

# SDR and GNU Radio
[radio-box]
image=ubuntu:22.04
pull=true
root=false
entry=false
init_hooks="sudo -u \#1000 bash ${HOME}/repos/coulomb/distrobox/init-radio-box.sh"
exported_apps=sdrpp gnuradio-companion gpredict fldigi
exported_bins=/usr/bin/gqrx /usr/bin/sdrpp /usr/bin/gnuradio-companion /usr/bin/gpredict /usr/bin/fldigi /usr/bin/inspectrum
